base modification

diff --git a/bin/setwal b/bin/setwal
--- a/bin/setwal
+++ b/bin/setwal
@@ -1,117 +1,203 @@
 #!/usr/bin/env bash
 
-# This script will set wallpaper and perform extra on user ask.
-[ $XDG_SESSION_TYPE = "wayland" ] || {
-  echo "This script is for wayland session."
-  echo "\$XDG_SESSION_TYPE is not wayland" 
-  exit
+check() {
+	command -v "$1" 1>/dev/null
 }
-WALLPATH="$HOME/Pictures/wallpapers"
-killall -q setwal
-check(){
-  command -v $1 1>/dev/null
-}
+
+# Variables
+_wallpath="$HOME/Pictures/wallpapers/"
 rootmgr="sudo"
 check doas && rootmgr="doas"
+_cmd="wbg"
+check swww && _cmd="swwwFn"
+skip=false
+green="\033[0;32m"
+nocolor="\033[0m"
 
-notify(){
-  check notify-send && {
-    notify-send \
-      --hint=string:x-dunst-stack-tag:wallpaper \
-      "$@"
-  } || {
-    echo "$@"
-  }
+# shellcheck disable=SC2015
+notify() {
+	check notify-send && {
+		notify-send \
+			--hint=string:x-dunst-stack-tag:wallpaper \
+			"$@"
+	} || {
+		echo "$@"
+	}
 }
 
-swwwSet(){
-  export SWWW_TRANSITION_FPS=60
-  export SWWW_TRANSITION_STEP=5
-  swww init &>/dev/null
-  swww img "$1"
+ok() {
+	echo -e "[$green  $nocolor] $*"
 }
 
-getImage(){
-  IFS=$'\n'$'\r'
-  wallpath="${WALLPATH:-$HOME/Pictures/wallpapers/}"
-  arr=($(find $wallpath -type f \( -iname '*.PNG' -o -iname '*.JPG' -o -iname '*.JPEG' \)))
-  echo "$(realpath ${arr[RANDOM%${#arr[@]}]})"
+err() {
+	echo -e "[$green  $nocolor] $*"
 }
 
-check wbg && setCmd="wbg"
-check swww && setCmd="swwwSet"
+# shellcheck disable=SC2120
+loading() {
+	pid=$! # Process Id of the previous running command
+	spin[0]="-"
+	spin[1]="\\"
+	spin[2]="|"
+	spin[3]="/"
 
-[ -z $setCmd ] && {
-  echo "Make sure wbg or swww is installed."
-  exit 1
+	echo -n "$1${spin[0]}"
+	while kill -0 $pid 2>/dev/null; do
+		for i in "${spin[@]}"; do
+			echo -ne "\b$i"
+			sleep 0.1
+		done
+	done
+	echo -ne "\b"
 }
 
-[ $# -gt 1 ] && {
-  echo "Invalid Args"
-  echo "If image name Contains space wrap it in \"name\" "
+swwwFn() {
+	export SWWW_TRANSITION_FPS=60
+	export SWWW_TRANSITION_STEP=5
+	swww init &>/dev/null
+	swww img "$1"
 }
 
-[ $# -eq 1 ] && {
-  ipath="$(realpath "$1")"
-  file "$ipath" | grep -qE 'image|bitmap' && {
-    imgPath="$ipath"
-  }
-}
-[ -z "$imgPath" ] && imgPath="$(getImage)"
-$setCmd "$imgPath" && {
-  notify "Image setted successfully" -i "$imgPath"
-  ln -sf "$imgPath" ~/.wallpaper
-}
-
-# extra
-
-oomox(){
-  notify -i "$imgPath" "Creating Gtk Theme OOMOX" -t 0
-  check sassc || {
-    echo "sassc not installed"
-    return
-  }
-  check bc || {
-    echo "bc not installed"
-    return
-  }
-  [ -f "$HOME/work/oomox-gtk-theme/change_color.sh" ] && {
-    $HOME/work/oomox-gtk-theme/change_color.sh -o oomox-gtk-nik-theme <(echo -e $(cat ~/.config/wpg/templates/oomox | sed 's/#//g'))
-  } || {
-    echo "Dir is not cloned in $HOME/work"
-  }
-  notify -i "$imgPath" "OMOX Generated" -t 0
+getimg() {
+	ipath="$(realpath "$1" 2>/dev/null)"
+	file "$ipath" | grep -qE 'image|bitmap' && {
+		echo "$ipath"
+		return
+	}
+	IFS=$'\n'$'\r'
+	wallpath="${WALLPATH:-$_wallpath}"
+	mapfile arr < <(find "$wallpath" -type f \( -iname '*.PNG' -o -iname '*.JPG' -o -iname '*.JPEG' \))
+	realpath "${arr[RANDOM % ${#arr[@]}]}"
 }
 
-ifffox(){
-  check fd || return
-  loc="$(fd -tf ^bg$ $HOME/.mozilla)"
-  /usr/bin/cp "$imgPath" "$loc"
+help() {
+	cat <<-EOF
+		This is setwal script by niksingh710.
+
+		ARGS:
+		  -s, --skip : Skips all extra steps and sets only the wallpaper.
+		  -t, --tool : Prints the tool binary name to be used to set wallpaper.
+		  -w, --wallpaper : Takes path to set as wallpaper 
+		                        if invalid image then chooses a random image.
+		  -tf, --toolforce : Forces the tool to be used to set wal
+	EOF
 }
 
-ifsddm(){
-  [ -d /usr/share/sddm/themes/sugar-candy/Backgrounds ] && {
-    $rootmgr /usr/bin/cp "$imgPath" /usr/share/sddm/themes/sugar-candy/Backgrounds/bg.jpg
-  }
+tool() {
+	echo "$_cmd" is going to be used
+	exit
 }
 
-wpg-settings(){
-  oomox   # Not using till linea is good from wpg-install.sh
-  check pywalfox && pywalfox update
-  check wal-telegram && wal-telegram --wal -r -g
-  check pywal-discord && pywal-discord
-  check mako && makoctl reload
-  check hyprctl && hyprctl reload
-  check pywal-discord && pywal-discord
-  ifsddm
-  ifffox
+# Extra fns
+
+oomox() {
+	notify -i "$_path" "Creating Gtk Theme OOMOX" -t 0
+	check sassc || {
+		notify "OOMOX: sassc not installed"
+		return 1
+	}
+	check bc || {
+		notify "OOMOX: bc not installed"
+		return 1
+	}
+
+	# shellcheck disable=SC2015
+	[ -f "$HOME/work/oomox-gtk-theme/change_color.sh" ] && {
+		"$HOME"/work/oomox-gtk-theme/change_color.sh \
+			-o oomox-gtk-nik-theme \
+			<(/usr/bin/cat "$HOME/.config/wpg/templates/oomox")
+	} || {
+		echo "Dir is not cloned in $HOME/work"
+	}
+	notify -i "$_path" "OMOX Generated" -t 0
 }
 
-check wpg && {
-  notify "Generating Colorscheme... " -i "$imgPath" -t 0
-  killall -q wpg
-  wpg -ns "$imgPath"
-  notify "Generated Colorscheme" -i "$imgPath" -t 0
-  wpg-settings
-  notify "Setted all Extra Stuff" "Whole system Refactored" -i "$imgPath"
+ifffox() {
+	check fd || return
+	loc=$(fd -tf "^bg$" "$HOME/.mozilla")
+	/usr/bin/cp "$_path" "$loc"
 }
+
+ifsddm() {
+	[ -d /usr/share/sddm/themes/sugar-candy/Backgrounds ] && {
+		$rootmgr /usr/bin/cp "$_path" /usr/share/sddm/themes/sugar-candy/Backgrounds/bg.jpg
+	}
+}
+
+extra() {
+	check pywalfox && pywalfox update
+	check wal-telegram && wal-telegram --wal -r -g
+	check pywal-discord && pywal-discord
+	check mako && makoctl reload
+	check pywal-discord && pywal-discord
+	check hyprctl && hyprctl reload
+	ifsddm
+	ifffox
+}
+
+wpg-settings() {
+	oomox &>/dev/null & # also generates or qt
+	# shellcheck disable=SC2015
+	loading && ok "Generated Oomox theme for qt and gtk" || err "Oomox Faced an err."
+	extra &>/dev/null &
+	# shellcheck disable=SC2015
+	loading && ok "Extra All went Fine" || err "Extra Failed..."
+}
+
+wpgFn() {
+	check wpg || return
+	notify "Generating Colorscheme... " -i "$_path" -t 0
+	killall -q wpg
+	wpg -ns "$_path"
+	notify "Generated Colorscheme" -i "$_path" -t 0
+}
+
+getArgs() {
+	while [ "$#" -gt 0 ]; do
+		case "$1" in
+		-s | --skip)
+			skip=true
+			;;
+		-t | --tool)
+			tool
+			;;
+		-tf | --toolforce)
+			_cmd="$2"
+			shift
+			;;
+		-w | --wallpaper)
+			_path="$(getimg "$2")"
+			shift
+			;;
+		-h | --help)
+			help
+			exit
+			;;
+		*)
+			help
+			echo ""
+			echo "Wrong argument given"
+			exit 1
+			;;
+		esac
+		shift
+	done
+}
+
+# echo "Welcome!! setting wallpaper"
+[ $# -eq 0 ] || getArgs "$@"
+
+[ -z "$_path" ] && _path="$(getimg)"
+$_cmd "$_path" && {
+	notify "Image setted successfully" -i "$_path"
+	ln -sf "$_path" ~/.wallpaper
+}
+$skip && exit 0
+
+wpgFn &>/dev/null &
+# shellcheck disable=SC2015
+loading && {
+	ok "Generated Colorschemes Using wpg"
+	wpg-settings
+	notify "Setted all Extra Stuff" "Whole system Refactored" -i "$_path"
+} || err "Wpg Faced Error"
