Added yt music theme in wpg and many more

diff --git a/hypr/scripts/cusfocus b/hypr/scripts/cusfocus
--- a/hypr/scripts/cusfocus
+++ b/hypr/scripts/cusfocus
@@ -1,24 +1,23 @@
 #!/bin/bash
 
 [ $# -eq 0 ] && {
-  echo "invalid move"
+	echo "invalid move"
 }
 
 [ "$1" = "cyclenext" ] && {
-  arg="none"
-  [ -z "$2" ] || arg="prev"
-  hyprctl dispatch cyclenext "$arg"
-  exit
+	arg="none"
+	[ -z "$2" ] || arg="prev"
+	hyprctl dispatch cyclenext "$arg"
+	exit
 }
 
 [[ "$1" =~ ^(l|r|u|d)$ ]] && {
-  [ "$(hyprctl activewindow -j | jq '.floating')" = true ] && {
-    arg=none
-    [[ "$1" =~ ^(l|u)$ ]] && arg='prev'
-    hyprctl dispatch cyclenext "$arg"
-  } || {
-    hyprctl dispatch movefocus "$1"
-  }
-  # hyprctl dispatch bringactivetotop none
+	[ "$(hyprctl activewindow -j | jq '.floating')" = true ] && {
+		arg=none
+		[[ "$1" =~ ^(l|u)$ ]] && arg='prev'
+		hyprctl dispatch cyclenext "$arg"
+		hyprctl dispatch bringactivetotop none
+	} || {
+		hyprctl dispatch movefocus "$1"
+	}
 }
-
